services:
  - type: web
    name: crawler-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 